package com.darkorbit

enum class BattleStationErrorCommandErrorType {
	/* 0 */ UNSPECIFIED,
	/* 1 */ NO_CLAN,
	/* 2 */ STATION_ALREADY_BUILDING,
	/* 3 */ ITEM_HITPOINTS_ZERO,
	/* 4 */ ITEM_ALREADY_EQUIPPED_IN_ANOTHER_ASTEROID,
	/* 5 */ CONCURRENT_EQUIP,
	/* 6 */ REPLACE_RIGHT_MISSING,
	/* 7 */ ITEM_NOT_OWNED,
	/* 8 */ OUT_OF_RANGE,
	/* 9 */ EQUIP_OF_SAME_PLAYER_RUNNING,
	/* 10 */ SATELLITE_ONLY,
	/* 11 */ HUB_ONLY,
	/* 12 */ ITEM_NOT_IN_STATION,
	/* 13 */ MAX_NUMBER_OF_MODULE_TYPE_EXCEEDED,
	/* 14 */ DEFLECTOR_NO_RIGHTS,
	/* 15 */ DEFLECTOR_ALREADY_OFF,
	/* 16 */ REPAIR_NO_MODULE,
	/* 17 */ REPAIR_NO_MONEY,
	/* 18 */ REPAIR_ALREADY_RUNNING,
	/* 19 */ UPGRADE_RUNNING,
}
