package com.darkorbit

enum class DispatchMessageCommandMessageType {
	/* 0 */ DISPATCH_SUCCESS_SEND_RETRIEVER,
	/* 1 */ DISPATCH_SUCCESS_SEND_GATE,
	/* 2 */ DISPATCH_SUCCESS_ADD_SLOT,
	/* 3 */ DISPATCH_ERROR_NO_GATE,
	/* 4 */ DISPATCH_ERROR_NO_SLOT,
	/* 5 */ DISPATCH_ERROR_NO_RESOURCE,
	/* 6 */ DISPATCH_ERROR_NOT_READY,
	/* 7 */ DISPATCH_ERROR_COLLECT,
	/* 8 */ DISPATCH_ERROR_SEND_RETRIEVER,
	/* 9 */ DISPATCH_ERROR_SEND_GATE,
	/* 10 */ DISPATCH_ERROR_INCOMPLETE_GATE,
	/* 11 */ DISPATCH_ERROR_MAX_SLOT,
}
