package com.darkorbit

enum class EventActivationStateCommandEventType {
	/* 0 */ FROSTED_GATES,
	/* 1 */ CHRISTMAS_TREES,
	/* 2 */ CARNIVAL_2013,
	/* 3 */ APRIL_FOOLS,
	/* 4 */ INFLUENCE_BATTLE,
	/* 5 */ INFLUENCE_BATTLE_VICTORY_BANNER,
	/* 6 */ MAP_REPLACEMENT,
	/* 7 */ EVENT_DOMINATING_FACTION,
	/* 8 */ DEMOLISHED_HQ,
	/* 9 */ BREACH,
	/* 10 */ ICEBERG,
	/* 11 */ PLAGUE_MOOD_ASSET,
	/* 12 */ PROPAGANDA_ASTEROIDS,
	/* 13 */ PROPAGANDA_ASTEROIDS_CARNIVAL,
	/* 14 */ PROPAGANDA_ASTEROIDS_EASTER2016,
	/* 15 */ PIXELATED_RENDERING_SETTING,
	/* 16 */ PERMAFROST_FISSURE_ASSEMBLY_WINDOW,
}
