package com.darkorbit

enum class OptionType {
	/* 0 */ FREE_PHOENIX,
	/* 1 */ BASIC_REPAIR,
	/* 2 */ AT_JUMPGATE_REPAIR,
	/* 3 */ AT_DEATHLOCATION_REPAIR,
	/* 4 */ AT_SECTOR_CONTROL_SPAWNPOINT,
	/* 5 */ EXIT_SECTOR_CONTROL,
	/* 6 */ BASIC_FULL_REPAIR,
	/* 7 */ RAID_GATE_REPAIR,
	/* 8 */ TDM_REPAIR,
	/* 9 */ PAYMENT,
	/* 10 */ REFRACTION_ZONE_FACTION_BASE,
	/* 11 */ REFRACTION_ZONE_DEATH_LOCATION,
	/* 12 */ WAR_GAME_REPAIR,
	/* 13 */ STRIKE_AND_EXIT,
}
