package com.darkorbit

enum class SoundType {
	/* 0 */ HELLSTORM_LAUNCHER_INITIATE_LOADING,
	/* 1 */ HELLSTORM_LAUNCHER_LOAD,
	/* 2 */ HELLSTORM_LAUNCHER_FULL,
	/* 3 */ NEW_SHIP_RECEIVED,
	/* 4 */ NPC_SLENDER_ATTACK,
	/* 5 */ NPC_SLENDER_MENACE,
	/* 6 */ NPC_SLENDER_REVEAL,
	/* 7 */ NPC_SLENDER_VANISH,
}
