package com.darkorbit

enum class WindowID {
	/* 0 */ USER_INFO,
	/* 1 */ SHIP_INFO,
	/* 2 */ QUEST,
	/* 3 */ LOG,
	/* 4 */ MINIMAP,
	/* 5 */ SETTINGS,
	/* 6 */ HELP,
	/* 7 */ TRADE,
	/* 8 */ SPACEMAP,
	/* 9 */ BOOSTER,
	/* 10 */ SPACEBALL,
	/* 11 */ INVASION,
	/* 12 */ CTB,
	/* 13 */ TDM,
	/* 14 */ CHAT,
	/* 15 */ CLI,
	/* 16 */ GROUP,
	/* 17 */ REFINEMENT,
	/* 18 */ ACHIEVEMENTS,
	/* 19 */ PET,
	/* 20 */ VIDEO_WINDOW,
	/* 21 */ ASSIST_WINDOW,
	/* 22 */ MINIMAP_WINDOW,
	/* 23 */ ADVERTISEMENT,
	/* 24 */ MENU_MAIN,
	/* 25 */ MENU_QUICK,
	/* 26 */ MENU_TOP,
}
